_imagine:
    resource: .
    type:     imagine

notice_show:
    pattern:  /notice/show.json
    defaults: { _controller: AnimeDbAppBundle:Notice:show, _format: json }

notice_close:
    pattern:  /notice/{id}/close.json
    defaults: { _controller: AnimeDbAppBundle:Notice:close, _format: json }
    requirements:
        _method:  POST
        id:  \d+