home:
    pattern:  /
    defaults: { _controller: AnimeDBCatalogBundle:Home:index }

home_search:
    pattern:  /search.html
    defaults: { _controller: AnimeDBCatalogBundle:Home:search }

home_autocomplete_name:
    pattern:  /autocomplete-name.json
    defaults: { _controller: AnimeDBCatalogBundle:Home:autocompleteName, _format: json }


item_add_manually:
    pattern:  /add-manually.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:addManually }

item_show:
    pattern:  /{id}-{name}/
    defaults: { _controller: AnimeDBCatalogBundle:Item:show }
    requirements:
        id:  \d+

item_change:
    pattern:  /{id}-{name}/change.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:change }
    requirements:
        id:  \d+

item_delete:
    pattern:  /{id}-{name}/delete.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:delete }
    requirements:
        id:  \d+

item_filler:
    pattern:  /filler/{plugin}.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:filler }

item_search:
    pattern:  /search/{plugin}.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:search }

item_import:
    pattern:  /import/{plugin}.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:import }


media_favicon:
    pattern:  /media/favicon/{host}.ico
    requirements:
        host: .+
    defaults: { _controller: AnimeDBCatalogBundle:Media:favicon }


form_local_path:
    pattern:  /form/local_path.html
    defaults: { _controller: AnimeDBCatalogBundle:Form:localPath }

form_local_path_folders:
    pattern:  /form/local_path/folders.json
    defaults: { _controller: AnimeDBCatalogBundle:Form:localPathFolders, _format: json }


form_image:
    pattern:  /form/image.html
    defaults: { _controller: AnimeDBCatalogBundle:Form:image }

form_image_upload:
    pattern:  /form/imageUpload.json
    defaults: { _controller: AnimeDBCatalogBundle:Form:imageUpload, _format: json }
    requirements:
        _method:  POST

storage_list:
    pattern:  /settings/storage.html
    defaults: { _controller: AnimeDBCatalogBundle:Storage:list }

storage_add:
    pattern:  /settings/storage/add.html
    defaults: { _controller: AnimeDBCatalogBundle:Storage:add }

storage_change:
    pattern:  /settings/storage/{id}/change.html
    defaults: { _controller: AnimeDBCatalogBundle:Storage:change }
    requirements:
        id:  \d+

storage_delete:
    pattern:  /settings/storage/{id}/delete.html
    defaults: { _controller: AnimeDBCatalogBundle:Storage:delete }
    requirements:
        id:  \d+
