services:
    anime_db.pagination:
        class: AnimeDB\Bundle\CatalogBundle\Service\Pagination

    # Plugins chain
    anime_db.plugin.filler:
        class: AnimeDB\Bundle\CatalogBundle\Service\Plugin\Filler\Chain
        scope: request
    anime_db.plugin.search:
        class: AnimeDB\Bundle\CatalogBundle\Service\Plugin\Search\Chain
        scope: request
    anime_db.plugin.import:
        class: AnimeDB\Bundle\CatalogBundle\Service\Plugin\Import\Chain
        scope: request
    anime_db.plugin.item:
        class: AnimeDB\Bundle\CatalogBundle\Service\Plugin\Item\Chain
        scope: request
    anime_db.plugin.setting:
        class: AnimeDB\Bundle\CatalogBundle\Service\Plugin\Setting\Chain
        scope: request

    # Twig extension
    anime_db.twig_extension:
        class: AnimeDB\Bundle\CatalogBundle\Service\TwigExtension
        arguments: [@router]
        tags:
            - { name: twig.extension }

    # cURL client for Buzz
    buzz.client.curl:
        class:  Buzz\Client\Curl
        public: false
        calls:
            - [setVerifyPeer, [false]]
    # Buzz browser
    buzz.browser:
        class:     Buzz\Browser
        arguments: ['@buzz.client.curl']

    # Kernel request listener
    anime_db.listener.request:
        class: AnimeDB\Bundle\CatalogBundle\Service\Listener\Request
        tags: [{ name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -255 }]
        arguments: [ @gedmo.listener.translatable ]

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
            - [ setDefaultLocale, [ %locale% ] ]
            - [ setTranslationFallback, [ true ] ]
