services:
    # Plugins chain
    anime_db.plugin.filler:
        class: AnimeDb\Bundle\CatalogBundle\Plugin\Filler\Chain
    anime_db.plugin.search:
        class: AnimeDb\Bundle\CatalogBundle\Plugin\Search\Chain
        arguments: [ %default_search% ]
    anime_db.plugin.import:
        class: AnimeDb\Bundle\CatalogBundle\Plugin\Import\Chain
    anime_db.plugin.item:
        class: AnimeDb\Bundle\CatalogBundle\Plugin\Item\Chain
    anime_db.plugin.setting:
        class: AnimeDb\Bundle\CatalogBundle\Plugin\Setting\Chain

    # Twig extension
    anime_db.twig_extension:
        class: AnimeDb\Bundle\CatalogBundle\Service\TwigExtension
        arguments: [@router]
        tags:
            - { name: twig.extension }

    anime_db.subscriber.scan_storage:
        class: AnimeDb\Bundle\CatalogBundle\Event\Subscriber\ScanStorage
        arguments: [ @doctrine.orm.entity_manager, @templating, @anime_db.plugin.search, @router ]
        tags: [{ name:kernel.event_subscriber }]
