services:
    anime_db.listener.update:
        class: AnimeDb\Bundle\AnimeDbBundle\Event\Listener\UpdateItself
        arguments: [ @anime_db.zip, %kernel.root_dir%, %anime_db.monitor% ]
        tags:
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeComposerRequirements }
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeConfigs }
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeBinRun }
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeBinService }
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedChangeAccessToFiles }

    anime_db.event_dispatcher:
        class: AnimeDb\Bundle\AnimeDbBundle\Event\Dispatcher
        calls:
            - [ setDispatcherDriver, [ @event_dispatcher ] ]

    anime_db.zip:
        class: ZipArchive
        public: false