parameters:
    serial_number: ""

    cron:
        enabled: false
        comands:
            - "0 1 1 * * animedb:check-updates"
            - "0 1 */3 * * animedb:scan-storage"
    task-manager:
        enabled: false