home:
    pattern:  /
    defaults: { _controller: AnimeDBCatalogBundle:Home:index }

home_selection:
    pattern:  /selection.html
    defaults: { _controller: AnimeDBCatalogBundle:Home:selection }

home_search:
    pattern:  /search.html
    defaults: { _controller: AnimeDBCatalogBundle:Home:search }

home_search_simple_form:
    pattern:  /search-simple-form.html
    defaults: { _controller: AnimeDBCatalogBundle:Home:searchSimpleForm }


item_add:
    pattern:  /add.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:add }

item_add_manually:
    pattern:  /add-manually.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:addManually }

item_show:
    pattern:  /{id}/
    defaults: { _controller: AnimeDBCatalogBundle:Item:show }
    requirements:
        id:  \d+

item_change:
    pattern:  /{id}/change.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:change }
    requirements:
        id:  \d+

item_remove:
    pattern:  /{id}/remove.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:remove }
    requirements:
        id:  \d+


filler_search:
    pattern:  /filler/search.html
    defaults: { _controller: AnimeDBCatalogBundle:Filler:search }

filler_fill:
    pattern:  /filler/fill.html
    defaults: { _controller: AnimeDBCatalogBundle:Filler:fill }
