parameters:

services:
     anime_db_catalog.autofill.chain:
        class: AnimeDB\CatalogBundle\Service\Autofill\Chain
     anime_db_catalog.autofill.worldartru:
        class: AnimeDB\CatalogBundle\Service\Autofill\Filler\WorldArtRu
        tags:
            -  { name: anime_db_catalog.autofill, alias: worldartru }
     anime_db_catalog.autofill.shikimoriorg:
        class: AnimeDB\CatalogBundle\Service\Autofill\Filler\ShikimoriOrg
        tags:
            -  { name: anime_db_catalog.autofill, alias: shikimoriorg }