services:
    anime_db.autofill:
        class: AnimeDB\CatalogBundle\Service\Autofill\Chain
        scope: request
    anime_db.autofill.worldartru:
        class: AnimeDB\CatalogBundle\Service\Autofill\Filler\WorldArtRu
        arguments: [@buzz.browser, @request, @doctrine]
        scope: request
        tags:
            -  { name: autofill.filler, alias: worldartru }
    anime_db.autofill.shikimoriorg:
        class: AnimeDB\CatalogBundle\Service\Autofill\Filler\ShikimoriOrg
        tags:
            -  { name: autofill.filler, alias: shikimoriorg }
    # Twig extension
    anime_db.twig_extension:
        class: AnimeDB\CatalogBundle\Service\TwigExtension
        tags:
            - { name: twig.extension }

    # cURL client for Buzz
    buzz.client.curl:
        class:  Buzz\Client\Curl
        public: false
        calls:
            - [setVerifyPeer, [false]]
    # Buzz browser
    buzz.browser:
        class:     Buzz\Browser
        arguments: ['@buzz.client.curl']