services:
    anime_db_catalog.autofill.chain:
        class: AnimeDB\CatalogBundle\Service\Autofill\Chain
        scope: request
    anime_db_catalog.autofill.worldartru:
        class: AnimeDB\CatalogBundle\Service\Autofill\Filler\WorldArtRu
        arguments: [@buzz.browser, @request, @doctrine]
        scope: request
        tags:
            -  { name: anime_db_catalog.autofill, alias: worldartru }
    anime_db_catalog.autofill.shikimoriorg:
        class: AnimeDB\CatalogBundle\Service\Autofill\Filler\ShikimoriOrg
        tags:
            -  { name: anime_db_catalog.autofill, alias: shikimoriorg }
    # Twig extension
    anime_db_catalog.twig.anime_db_extension:
        class: AnimeDB\CatalogBundle\Service\Twig\AnimeDBExtension
        tags:
            - { name: twig.extension }

    # cURL client for Buzz
    buzz.client.curl:
        class:  Buzz\Client\Curl
        public: false
        calls:
            - [setVerifyPeer, [false]]
    # Buzz browser
    buzz.browser:
        class:     Buzz\Browser
        arguments: ['@buzz.client.curl']