services:
    anime_db.listener.update:
        class: AnimeDb\Bundle\AnimeDbBundle\Event\Listener\UpdateItself
        arguments: [ %kernel.root_dir% ]
        tags:
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeComposerRequirements }
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeAppKernalBundles }
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeBinRun }
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeBinService }