services:
    anime_db.listener.update:
        class: AnimeDb\Bundle\AnimeDbBundle\Event\Listener\Update
        tags:
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeComposerRequirements }
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeAppKernalBundles }
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeBinRun }