services:
    anime_db.listener.update:
        class: AnimeDb\Bundle\AnimeDbBundle\Event\Listener\UpdateItself
        arguments: [ %kernel.root_dir% ]
        tags:
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeComposerRequirements }
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeConfigs }
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeBinRun }
            - { name: kernel.event_listener, event: anime_db.update_itself.downloaded, method: onAppDownloadedMergeBinService }

    anime_db.event_dispatcher:
        class: AnimeDb\Bundle\AnimeDbBundle\Event\Dispatcher
        calls:
            - [ setDispatcherDriver, [ @event_dispatcher ] ]